---
networks:
  jenkins:
    name: jenkins
    driver: bridge
services:
  docker:
    command: --storage-driver overlay2 --config-file /etc/docker/daemon.json
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    image: docker:dind
    networks:
      - jenkins
    privileged: true
    restart: unless-stopped
    volumes:
      - docker-certs:/certs/client
      - data:/var/jenkins_home
      - ./docker:/etc/docker:ro
  server:
    depends_on:
      - docker
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    image: jenkins-server:2.492.3-lts-jdk17
    networks:
      - jenkins
    ports:
      - 8080:8080
      - 50000:50000
    restart: unless-stopped
    volumes:
      - data:/var/jenkins_home
      - docker-certs:/certs/client:ro

volumes:
  data:
  docker-certs:
